create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  email text,
  created_at text not null
);

create table if not exists public.user_migrations (
  legacy_user_id bigint primary key,
  supabase_user_id text not null unique,
  username text not null,
  migrated_at text not null
);

create table if not exists public.images (
  id bigint generated by default as identity primary key,
  user_id text not null,
  prompt text not null,
  model_name text not null,
  dimensions text not null,
  image_path text not null,
  category text not null check (category in ('favorite', 'backup', 'discarded')),
  reference_images text not null,
  created_at text not null
);

create table if not exists public.generations (
  id bigint generated by default as identity primary key,
  user_id text not null,
  username text not null,
  prompt text not null,
  model_id text not null,
  model_name text not null,
  dimensions text not null,
  image_size text not null default '',
  image_path text not null,
  credits_used integer not null,
  reference_images text not null,
  created_at text not null
);

create table if not exists public.user_credits (
  user_id text primary key,
  username text not null,
  total_credits integer not null,
  used_credits integer not null default 0,
  created_at text not null,
  updated_at text not null
);

create table if not exists public.invite_codes (
  code text primary key,
  credits integer not null,
  issued_credits integer not null default 0,
  created_by text not null,
  created_at text not null,
  redeemed_by text,
  redeemed_at text,
  low_balance_since text
);

create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at text not null
);

create index if not exists images_user_category_created_idx
  on public.images (user_id, category, created_at desc, id desc);

create index if not exists generations_user_created_idx
  on public.generations (user_id, created_at desc, id desc);

create index if not exists generations_created_idx
  on public.generations (created_at desc, id desc);

create index if not exists invite_codes_redeemed_by_idx
  on public.invite_codes (redeemed_by);

alter table public.users enable row level security;
alter table public.user_migrations enable row level security;
alter table public.images enable row level security;
alter table public.generations enable row level security;
alter table public.user_credits enable row level security;
alter table public.invite_codes enable row level security;
alter table public.app_settings enable row level security;
